# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: mysql
#    restart: always
#    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "/usr/local/opt/mysql/8.0:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: test
      MYSQL_PASS: 123456
